DROP TABLE IF EXISTS settings;
CREATE TABLE settings (
  id      INTEGER PRIMARY KEY AUTOINCREMENT,
  title   TEXT NOT NULL,
  content TEXT NOT NULL
);


DROP TABLE IF EXISTS servers;
CREATE TABLE servers (
  id       INTEGER PRIMARY KEY AUTOINCREMENT,
  ip       TEXT NOT NULL,
  role     TEXT NOT NULL,
  password TEXT NOT NULL
);


